-- MySQL Script generated by MySQL Workbench
-- Thu Feb 23 08:26:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `school2` ;

-- -----------------------------------------------------
-- Schema school2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school2` DEFAULT CHARACTER SET utf8 ;
USE `school2` ;

-- -----------------------------------------------------
-- Table `school2`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`class` ;

CREATE TABLE IF NOT EXISTS `school2`.`class` (
  `school_year` YEAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`school_year`, `grade`, `room`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`status` ;

CREATE TABLE IF NOT EXISTS `school2`.`status` (
  `status_id` INT NOT NULL,
  `status_name` VARCHAR(45) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`teacher` ;

CREATE TABLE IF NOT EXISTS `school2`.`teacher` (
  `teacher_id` VARCHAR(6) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `fist_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `solial_id` VARCHAR(13) NOT NULL,
  `bathday` DATE NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `first_name_father` VARCHAR(45) NOT NULL,
  `last_name_father` VARCHAR(45) NOT NULL,
  `first_name_mother` VARCHAR(45) NOT NULL,
  `last_name_mother` VARCHAR(45) NOT NULL,
  `fist_name_parent` VARCHAR(45) NOT NULL,
  `last_name_parent` VARCHAR(45) NOT NULL,
  `phone_number_of_parent` VARCHAR(10) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`teacher_id`),
  INDEX `fk_teacher_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_teacher_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `school2`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`advicers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`advicers` ;

CREATE TABLE IF NOT EXISTS `school2`.`advicers` (
  `school_year` YEAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  `teacher_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`school_year`, `grade`, `room`, `teacher_id`),
  UNIQUE INDEX `school_year` (`school_year` ASC, `grade` ASC, `room` ASC, `teacher_id` ASC),
  INDEX `teacher_id` (`teacher_id` ASC),
  CONSTRAINT `advicers_ibfk_1`
    FOREIGN KEY (`school_year` , `grade` , `room`)
    REFERENCES `school2`.`class` (`school_year` , `grade` , `room`),
  CONSTRAINT `advicers_ibfk_2`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school2`.`teacher` (`teacher_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`subject` ;

CREATE TABLE IF NOT EXISTS `school2`.`subject` (
  `subject_id` VARCHAR(6) NOT NULL,
  `subject_name` VARCHAR(45) NOT NULL,
  `course_description_th` VARCHAR(500) NOT NULL,
  `course_description_en` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`evaluation` ;

CREATE TABLE IF NOT EXISTS `school2`.`evaluation` (
  `subject_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR(4) NOT NULL,
  `A` DECIMAL(4,2) NOT NULL,
  `B+` DECIMAL(4,2) NOT NULL,
  `B` DECIMAL(4,2) NOT NULL,
  `C+` DECIMAL(4,2) NOT NULL,
  `C` DECIMAL(4,2) NOT NULL,
  `D+` DECIMAL(4,2) NOT NULL,
  `D` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`subject_id`, `school_year`),
  INDEX `fk_evaluation_subject1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_evaluation_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school2`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`student` ;

CREATE TABLE IF NOT EXISTS `school2`.`student` (
  `student_id` VARCHAR(6) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `fist_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `solial_id` VARCHAR(13) NOT NULL,
  `bathday` DATE NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `first_name_father` VARCHAR(45) NOT NULL,
  `last_name_father` VARCHAR(45) NOT NULL,
  `first_name_mother` VARCHAR(45) NOT NULL,
  `last_name_mother` VARCHAR(45) NOT NULL,
  `fist_name_parent` VARCHAR(45) NOT NULL,
  `last_name_parent` VARCHAR(45) NOT NULL,
  `phone_number_of_parent` VARCHAR(10) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_student_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_student_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `school2`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`student_has_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`student_has_class` ;

CREATE TABLE IF NOT EXISTS `school2`.`student_has_class` (
  `student_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`student_id`, `school_year`, `grade`, `room`),
  INDEX `fk_student_has_class_class1_idx` (`school_year` ASC, `grade` ASC, `room` ASC),
  INDEX `fk_student_has_class_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_student_has_class_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `school2`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_class_class1`
    FOREIGN KEY (`school_year` , `grade` , `room`)
    REFERENCES `school2`.`class` (`school_year` , `grade` , `room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`enroll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`enroll` ;

CREATE TABLE IF NOT EXISTS `school2`.`enroll` (
  `student_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  `enroll_subject_id` INT NOT NULL,
  PRIMARY KEY (`student_id`, `school_year`, `grade`, `room`, `enroll_subject_id`),
  INDEX `fk_student_has_class_has_teacher_student_has_class1_idx` (`student_id` ASC, `school_year` ASC, `grade` ASC, `room` ASC),
  CONSTRAINT `fk_student_has_class_has_teacher_student_has_class1`
    FOREIGN KEY (`student_id` , `school_year` , `grade` , `room`)
    REFERENCES `school2`.`student_has_class` (`student_id` , `school_year` , `grade` , `room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`score` ;

CREATE TABLE IF NOT EXISTS `school2`.`score` (
  `score_id` INT(11) NOT NULL,
  `score_evaluation` VARCHAR(45) NOT NULL,
  `max_score` DECIMAL(7,2) NOT NULL,
  `point` DECIMAL(7,2) NOT NULL,
  `percent` DECIMAL(5,2) NOT NULL,
  `student_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  `teacher_id` VARCHAR(6) NOT NULL,
  `subject_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`score_id`),
  INDEX `fk_score_enroll1_idx` (`student_id` ASC, `school_year` ASC, `grade` ASC, `room` ASC, `teacher_id` ASC, `subject_id` ASC),
  CONSTRAINT `fk_score_enroll1`
    FOREIGN KEY (`student_id` , `school_year` , `grade` , `room`)
    REFERENCES `school2`.`enroll` (`student_id` , `school_year` , `grade` , `room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`enroll_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`enroll_subject` ;

CREATE TABLE IF NOT EXISTS `school2`.`enroll_subject` (
  `enroll_subject_id` INT NOT NULL,
  `teacher_id` VARCHAR(6) NOT NULL,
  `subject_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`enroll_subject_id`),
  INDEX `fk_enroll_subject_teacher1_idx` (`teacher_id` ASC),
  INDEX `fk_enroll_subject_subject1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_enroll_subject_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school2`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enroll_subject_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school2`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`time_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`time_table` ;

CREATE TABLE IF NOT EXISTS `school2`.`time_table` (
  `time_table_id` INT NOT NULL,
  `school_year` YEAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  `time` TIME NULL,
  `term` VARCHAR(1) NULL,
  `enroll_subject_id` INT NOT NULL,
  PRIMARY KEY (`time_table_id`),
  INDEX `fk_time_table_class1_idx` (`school_year` ASC, `grade` ASC, `room` ASC),
  INDEX `fk_time_table_enroll_subject1_idx` (`enroll_subject_id` ASC),
  CONSTRAINT `fk_time_table_class1`
    FOREIGN KEY (`school_year` , `grade` , `room`)
    REFERENCES `school2`.`class` (`school_year` , `grade` , `room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_time_table_enroll_subject1`
    FOREIGN KEY (`enroll_subject_id`)
    REFERENCES `school2`.`enroll_subject` (`enroll_subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `school2`.`work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school2`.`work` ;

CREATE TABLE IF NOT EXISTS `school2`.`work` (
  `work_id` INT NOT NULL,
  `work_name` VARCHAR(45) NULL,
  `work_details` VARCHAR(500) NULL,
  `enroll_subject_id` INT NOT NULL,
  PRIMARY KEY (`work_id`),
  INDEX `fk_work_enroll_subject1_idx` (`enroll_subject_id` ASC),
  CONSTRAINT `fk_work_enroll_subject1`
    FOREIGN KEY (`enroll_subject_id`)
    REFERENCES `school2`.`enroll_subject` (`enroll_subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
