-- MySQL Script generated by MySQL Workbench
-- Sat Feb 11 15:13:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` DEFAULT CHARACTER SET utf8 ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`student` (
  `student_id` VARCHAR(6) NOT NULL,
  `password` VARCHAR(32) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `soiial_id` VARCHAR(13) NULL,
  `bathday` DATE NULL,
  `nationality` VARCHAR(45) NULL,
  `phone_number` VARCHAR(10) NULL,
  `first_name_father` VARCHAR(45) NULL,
  `last_name_father` VARCHAR(45) NULL,
  `first_name_mother` VARCHAR(45) NULL,
  `last_name_mother` VARCHAR(45) NULL,
  `first_name_parent` VARCHAR(45) NULL,
  `last_name_parent` VARCHAR(45) NULL,
  `phone_number_of_parent` VARCHAR(10) NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`class` (
  `school_year` YEAR NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`school_year`, `room`, `grade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`teacher` (
  `teacher_id` VARCHAR(6) NOT NULL,
  `password` VARCHAR(32) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `soiial_id` VARCHAR(13) NULL,
  `bathday` DATE NULL,
  `nationality` VARCHAR(45) NULL,
  `phone_number` VARCHAR(10) NULL,
  `first_name_father` VARCHAR(45) NULL,
  `last_name_father` VARCHAR(45) NULL,
  `first_name_mother` VARCHAR(45) NULL,
  `last_name_mother` VARCHAR(45) NULL,
  `first_name_parent` VARCHAR(45) NULL,
  `last_name_parent` VARCHAR(45) NULL,
  `phone_number_of_parent` VARCHAR(10) NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`advicers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`advicers` (
  `teacher_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`teacher_id`, `school_year`, `room`, `grade`),
  INDEX `fk_teacher_has_class_class1_idx` (`school_year` ASC, `room` ASC, `grade` ASC) VISIBLE,
  INDEX `fk_teacher_has_class_teacher_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_has_class_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teacher_has_class_class1`
    FOREIGN KEY (`school_year` , `room` , `grade`)
    REFERENCES `school`.`class` (`school_year` , `room` , `grade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`student_has_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`student_has_class` (
  `student_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`student_id`, `school_year`, `room`, `grade`),
  INDEX `fk_student_has_class_class1_idx` (`school_year` ASC, `room` ASC, `grade` ASC) VISIBLE,
  INDEX `fk_student_has_class_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_class_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `school`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_class_class1`
    FOREIGN KEY (`school_year` , `room` , `grade`)
    REFERENCES `school`.`class` (`school_year` , `room` , `grade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`subject` (
  `subject_id` VARCHAR(6) NOT NULL,
  `subject_name` VARCHAR(45) NULL,
  `course_description_th` VARCHAR(500) NULL,
  `course_description_en` VARCHAR(500) NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`enroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`enroll` (
  `student_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `teacher_id` VARCHAR(6) NOT NULL,
  `subject_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`student_id`, `school_year`, `room`, `grade`, `teacher_id`, `subject_id`),
  INDEX `fk_student_has_class_has_teacher_teacher1_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_student_has_class_has_teacher_student_has_class1_idx` (`student_id` ASC, `school_year` ASC, `room` ASC, `grade` ASC) VISIBLE,
  INDEX `fk_enroll_subject1_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_class_has_teacher_student_has_class1`
    FOREIGN KEY (`student_id` , `school_year` , `room` , `grade`)
    REFERENCES `school`.`student_has_class` (`student_id` , `school_year` , `room` , `grade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_class_has_teacher_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enroll_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`score` (
  `score_id` INT NOT NULL,
  `score_evaluation` VARCHAR(45) NULL,
  `max_score` DECIMAL(7,2) NULL,
  `point` DECIMAL(7,2) NULL,
  `percent` DECIMAL(5,2) NULL,
  `student_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR NOT NULL,
  `room` VARCHAR(4) NOT NULL,
  `grade` VARCHAR(4) NOT NULL,
  `teacher_id` VARCHAR(6) NOT NULL,
  `subject_id` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`score_id`),
  INDEX `fk_score_enroll1_idx` (`student_id` ASC, `school_year` ASC, `room` ASC, `grade` ASC, `teacher_id` ASC, `subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_score_enroll1`
    FOREIGN KEY (`student_id` , `school_year` , `room` , `grade` , `teacher_id` , `subject_id`)
    REFERENCES `school`.`enroll` (`student_id` , `school_year` , `room` , `grade` , `teacher_id` , `subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`evaluations` (
  `subject_id` VARCHAR(6) NOT NULL,
  `school_year` YEAR NOT NULL,
  `A` DECIMAL(4,2) NULL,
  `B+` DECIMAL(4,2) NULL,
  `B` DECIMAL(4,2) NULL,
  `C+` DECIMAL(4,2) NULL,
  `C` DECIMAL(4,2) NULL,
  `D+` DECIMAL(4,2) NULL,
  `D` DECIMAL(4,2) NULL,
  `F` DECIMAL(4,2) NULL,
  PRIMARY KEY (`subject_id`, `school_year`),
  INDEX `fk_evaluations_subject1_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_evaluations_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
